// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

Future<List<PortInfo>> getPortList() =>
    RustLib.instance.api.crateApiMainGetPortList();

Future<PortInfo> connectPort({required String portName}) =>
    RustLib.instance.api.crateApiMainConnectPort(portName: portName);

Future<void> writeFile({
  required String portName,
  required String fName,
  required String tgFile,
  required String options,
  required Config config,
}) => RustLib.instance.api.crateApiMainWriteFile(
  portName: portName,
  fName: fName,
  tgFile: tgFile,
  options: options,
  config: config,
);

Future<void> main() => RustLib.instance.api.crateApiMainMain();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Box < dyn Error + Send + Sync >>>
abstract class BoxError implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PortInfo>>
abstract class PortInfo implements RustOpaqueInterface {
  String get portName;

  SerialPortType get portType;

  set portName(String portName);

  set portType(SerialPortType portType);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< SerialPortType>>
abstract class SerialPortType implements RustOpaqueInterface {}

class Config {
  final int baudrate;
  final int dataBlockSize;
  final bool printReplWhlieWriting;

  const Config({
    required this.baudrate,
    required this.dataBlockSize,
    required this.printReplWhlieWriting,
  });

  @override
  int get hashCode =>
      baudrate.hashCode ^
      dataBlockSize.hashCode ^
      printReplWhlieWriting.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Config &&
          runtimeType == other.runtimeType &&
          baudrate == other.baudrate &&
          dataBlockSize == other.dataBlockSize &&
          printReplWhlieWriting == other.printReplWhlieWriting;
}
